### PR TITLE
Add rudimentary UI components

### PR DESCRIPTION
**Pull request by alanaalfeche**
There are 7 UI components added in this PR:
1. /join: allows a player to pick a character from a default drop-down list and send request to APP.server.send_join_request(). The response is the client_id. 

Screen Shot 2020-04-22 at 12 05 30 AM

2. /queue/client_id:  is a redirect from the join page. It has a button that says `start a game` which send a request to APP.server.send_start_game_request() to start the game. The response is the game_id. 

Screen Shot 2020-04-21 at 7 20 35 PM

3. /game/<game_id>/<client_id>/suggest is a redirect from the queue page when the number of players has reached the minimum value (3). It provides a page where the first turn can make a suggestion. In this case, it will always be the last person who joined the game. The character is dynamic, but the location is hardcoded. 
Screen Shot 2020-04-22 at 12 05 44 AM

4. /result/<game_id>/<client_id> is the results page after suggestion. It provides the player two options: make accusation or move and end their turn. The result is hardcoded.
Screen Shot 2020-04-22 at 12 05 52 AM

5. /accuse/<game_id>/<client_id> is rendered when the player chose to make an accusation. 
Screen Shot 2020-04-22 at 12 06 00 AM

When the user hits submit, message value appears. This value is hardcoded.
Screen Shot 2020-04-22 at 12 06 08 AM

6. /move/<game_id>/<client_id is loaded when the player choose to move. The options are correct but they're hardcoded.

Screen Shot 2020-04-22 at 12 06 25 AM

When the user hits submit, message value appears. This value is hardcoded.
Screen Shot 2020-04-22 at 12 06 32 AM

7. Lastly, the game minimum threshold. As shown below, we would need to register user 5001-5003 because we can move pass queue page. 

**User1 - localhost:5001** receives the wait message because number of registered players hasn't reached minimum threshold yet (3)
Screen Shot 2020-04-21 at 7 20 27 PM
Screen Shot 2020-04-21 at 7 20 35 PM
Screen Shot 2020-04-21 at 7 20 40 PM

**User 2 - localhost:5002** receives the wait message because number of registered players hasn't reached minimum threshold yet (3)
Screen Shot 2020-04-21 at 7 21 00 PM

**User 3- localhost:5003** finally makes it to the accusation page 
Screen Shot 2020-04-21 at 7 21 11 PM

### CODE REVIEW

**Comment by addisonhammer** [comment]
Removed some DEBUG flags that weren't working as expected. Merge and try again?

**Comment by alanaalfeche** [comment]
I have the lastest master unfortunately

**Comment by addisonhammer** [comment]
Re: Issue 2 - Not sure about this one. 
#### current function definition:
```
@APP.route('/api/start_game', methods=['GET'])
def start_game():
    start_request = StartGameRequest.from_dict(request.args)
     ...
```
#### current message definition
```
@attr.s(auto_attribs=True, slots=True)
class StartGameRequest(Message):
    player: str
    client_id: str
```
Doesn't look like it should need game_id, and I generate game_id later in that same method and send it in the response:
```

@attr.s(auto_attribs=True, slots=True)
class StartGameResponse(Message):
    """This is the response to the client asking to start the game"""
    player: str
    game_id: str
    accepted: bool
    player_count: int
```

**Comment by alanaalfeche** [comment]
> Removed some DEBUG flags that weren't working as expected. Merge and try again?

Hm, send_join_request actually only returns a boolean instead of the client id. Issue #1 is fixed.

**Comment by alanaalfeche** [comment]
@addisonhammer this is what I am trying to send my request to: 
https://github.com/addisonhammer/clue-less/blob/master/core/server_boundary.py#L33

**Pull request merged**
